import { Project } from '../interfaces';
//projects info
export const projectsInfo: Project[] = (() => [
  {
    id: 'coding-environment',
    image: {
      src: 'code-env.png',
      alt: 'coding-environement',
    },
    name: 'Coding Environment',
    title: 'Web Coding Environment',
    description:
      'This is an interactive coding environment. You can write Javascript, see it compiled, and write comprehensive documentation / notes using a Markdown Editor. This project uses a CLI to start a local express API that serves the react app. Visit this link to try it!',
    github: 'web-coding-env',
    website: '',
    skills: [
      {
        title: 'Typescript',
        logo: 'logo-ts.svg',
        alt: 'Typescript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Redux', logo: 'logo-redux.svg', alt: 'ReduxJS', span: false },
      {
        title: 'Responsive CSS3',
        logo: 'logo-css.svg',
        alt: 'CSS3',
        span: true,
      },
      { title: 'Node', logo: 'logo-node.svg', alt: 'NodeJS', span: true },
      {
        title: 'Express',
        logo: '',
        alt: 'ExpressJS',
        span: false,
      },
      { title: 'CLI', logo: 'logo-cli.svg', alt: 'CLI', span: true },
      { title: 'Lerna', logo: '', alt: 'Lerna', span: false },
    ],
  },
  {
    id: 'rest-api',
    image: {
      src: 'rest-home-dark.jpg',
      alt: 'rest-countries-api',
    },
    name: 'Rest API',
    title: 'Rest API Web App',
    description: 'This is a rest countries app',
    github: 'rest-countries-api',
    website: 'https://rest-countries-api-nightclover-code.vercel.app/',
    skills: [
      {
        title: 'Typescript',
        logo: 'logo-ts.svg',
        alt: 'Typescript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Redux', logo: 'logo-redux.svg', alt: 'ReduxJS', span: false },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: false },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: true },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: false,
      },
    ],
  },
  {
    id: 'url-shortener',
    name: 'Url Shortener',
    image: {
      src: 'url-shortener.jpg',
      alt: 'url-shortener',
    },
    title: 'Shortly - Url Shortener Website',
    description: 'This is an url shortener website',
    github: 'url-shortener',
    website: 'https://url-shortener-git-main-nightclover-code.vercel.app/',
    skills: [
      {
        title: 'Modern Javascript',
        logo: 'logo-js.svg',
        alt: 'Javascript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Redux', logo: 'logo-redux.svg', alt: 'ReduxJS', span: false },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: false },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: false },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: false,
      },
      {
        title: 'Firebase',
        logo: 'logo-firebase.svg',
        alt: 'Firebase',
        span: false,
      },
    ],
  },
  {
    id: 'newsly',
    name: 'Newsly',
    image: {
      src: 'newsly.png',
      alt: 'newsly',
      objectPosition: '0 0',
    },
    title: 'Newsly - News Web App (In Progress)',
    description: 'This is a news related website',
    github: 'newsly',
    website: 'https://newsly-nightclover-code.vercel.app/',
    skills: [
      {
        title: 'Typescript',
        logo: 'logo-ts.svg',
        alt: 'Typescript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: false },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: false },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: true,
      },
      { title: 'Figma', logo: 'logo-figma.svg', alt: 'Figma', span: false },
    ],
  },
  {
    id: 'bookmark',
    name: 'Bookmark',
    image: {
      src: 'bookmark.jpg',
      alt: 'bookmark',
    },
    title: 'Bookmark - Extensions Manager Website',
    description: 'This is a bookmarking related website',
    github: 'bookmark',
    website: 'https://bookmark-git-master-nightclover-code.vercel.app/',
    skills: [
      {
        title: 'Typescript',
        logo: 'logo-ts.svg',
        alt: 'Typescript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: false },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: true },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: true,
      },
    ],
  },
  {
    id: 'todo-app',
    name: 'Todo App',
    image: {
      src: 'todo-app-dark.jpg',
      alt: 'todo-app',
    },
    title: 'TODO - Todo Web App',
    description: 'This is a todos related website',
    github: 'todo-app',
    website: 'https://stoic-wiles-03feb7.netlify.app/',
    skills: [
      {
        title: 'Modern Javascript',
        logo: 'logo-js.svg',
        alt: 'Javascript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: false },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: true },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: true,
      },
    ],
  },
  {
    id: 'room',
    name: 'Room Hompage',
    image: {
      src: 'room-slide-1.jpg',
      alt: 'room',
    },
    title: 'Room - eCommerce Homepage Website',
    description: 'This is a room related website',
    github: 'room-homepage-ecommerce',
    website:
      'https://room-homepage-ecommerce-git-master-nightclover-code.vercel.app/',
    skills: [
      {
        title: 'Modern Javascript',
        logo: 'logo-js.svg',
        alt: 'Javascript',
        span: false,
      },
      { title: 'React', logo: 'logo-react.svg', alt: 'ReactJS', span: true },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: false },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: true },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: true,
      },
    ],
  },
  {
    id: 'chat-app',
    name: 'Chat App',
    image: {
      src: 'chat-app.jpg',
      alt: 'chat-app',
    },
    title: 'Simple Booking - Chat App Illustration',
    description: 'This is a chat app illustration',
    github: 'css-illustration',
    website: 'http://css-illustration-git-master.nightclover-code.vercel.app/',
    skills: [
      {
        title: 'Semantic HTML5',
        logo: 'logo-html.svg',
        alt: 'HTML5',
        span: true,
      },
      { title: 'Sass', logo: 'logo-sass.svg', alt: 'Sass', span: true },
      { title: 'git', logo: 'logo-git.svg', alt: 'git', span: true },
      {
        title: 'github',
        logo: 'logo-github-skills.svg',
        alt: 'github',
        span: true,
      },
    ],
  },
])();
